// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiggtaqzimasxmvxoucy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZ2d0YXF6aW1hc3htdnhvdWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTY4MzcsImV4cCI6MjA2NjMzMjgzN30.SJFRln9eKZjUrh2LNWEoiJciGFoLoOg829c-huE9FMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);